### ISSUE TITLE
Unity soundtrack

### ISSUE THREAD

**Issue by markanini** [coelckers/gzdoom#1268]
Unity soundtrack isn't currently supported. Please allow GZDoom to search for Steam paths:
C:\Program Files (x86)\Steam\steamapps\common\Ultimate Doom\rerelease\DOOM_Data\StreamingAssets\Soundtrack
C:\Program Files (x86)\Steam\steamapps\common\Doom 2\rerelease\DOOM II_Data\StreamingAssets\Soundtrack 

A second issue is that the Unity soundtrack uses some different titles than what GZDoom expects. 
For Ultimate doom:
Expected: d_inter - Unity: d_e2m3
Expected: d_e2m5 & d_e3m5 - Unity: d_e1m7
Expected: d_e3m1 - Unity: d_e2m9
Expected: d_e3m4 - Unity: d_e1m8
Expected: d_e3m5 - Unity: d_e1m7
Expected: d_e3m6 - Unity: d_e1m6
Expected: d_e3m7 - Unity: d_e2m7
Expected: d_e3m9 - Unity: d_e1m9

For Doom 2:
Expected: d_count2 - Unity: d_countd
Expected: d_ddtbl2 & d_ddtbl3 - Unity: d_ddtblu 
Expected: d_dead2 - Unity: d_dead 
Expected: d_doom2 - Unity: d_doom 
Expected: d_messg2 - Unity: d_messag 
Expected: d_romer2 - Unity: d_romero 
Expected: d_runni2 - Unity: d_runnin 
Expected: d_shawn2 & d_shawn3 - Unity: d_shawn 
Expected: d_stlks2 & d_stlks3 - Unity: d_stalks 
Expected: d_theda2 & d_theda3 - Unity: d_the_da

**Comment by madame-rachelle** [comment]
The soundtrack is already natively supported, when loading the Unity version from Steam it's already there. (There is a bug however that it cannot support external Steam libraries - so make sure to install to your C drive if you haven't already) As for the file renames however ..... talk about moving target. I'm sorry but the fact that Unity Doom refuses to duplicate the files is in my opinion a system broken by design. How are mods supposed to override this if they use the renamed files? If it detects the tracks and allows the mod to replace them anyway ... yuck, sorry but this is a bridge too far for me.

I'll let @coelckers have the final word on this, but I'm of the opinion I don't want to give much more support to the Unity versions than I already have. They are constantly moving the goal posts and it makes it really not worth the time to invest in it until such time they decide it's in a solid state and that it's time to stop making changes. In the meantime, the relevant files can be copied and put into an archive manually, as needed. Or I could even write a shell script, both for Linux and Windows, that symlinks the files for you.

**Comment by madame-rachelle** [comment]
I'm going to say here unequivocally, if Bethesda wants to foster source port support for the newer versions of Doom, they're going to have to work *with* us, not regardless of us.

**Comment by coelckers** [comment]
The proper way to handle the music would be $musicalias redirections so that it doesn't get in the way of PWADs.
I can understand why they do not want to duplicate the music files, considering their size.

**Comment by madame-rachelle** [comment]
Indeed, sorry for my rant, just not happy with being kept in the dark about changes like this, that's all.

**Comment by coelckers** [comment]
Same here. Chasing a moving target can be very annoying.

**Comment by madame-rachelle** [comment]
Fixed. Had to change it so it would accept IWad music renames when called from game_support.pk3.

**Comment by drfrag666** [comment]
So is this right? I think it is.
https://github.com/drfrag666/gzdoom/commit/76e3f4c8f52041596c0281ba4fda43cd1521aaf9
