### ISSUE TITLE
Hexen format maps assume "Monster Activates" for non-Monster doors with a speed less than 64.

### ISSUE THREAD

**Issue by Acts19quiz** [coelckers/gzdoom#1326]
Tested: GZDoom 4.5.0 for Windows and (among other things) ZDoom 2.8.1, Zandronum 3.0, ZDaemon 1.10.15, LZDoom 3.87c

I spotted something weird while mapping and testing (in Chex Quest 3's E3M5, actually), and created a test map to confirm what I thought was happening (included below). In a Hexen format map, doors with a speed less than 64 will permit monster activation on "Player presses Use" actions regardless of whether or not "Monster Activates" is selected. It should be noted that in original Doom format, doors do this by default (16 or slow doors allow monster activation, while fast doors don't), but that's a limitation of the number of different kind of door activators. The Hexen customization seems to be ignored here.

A version of the provided test map saved in UDMF didn't exhibit this issue. Odamex is the only ZDoom fork I tested that correctly interpreted the Hexen flags (Eternity Hexen support doesn't seem to be quite there yet).

Am I missing something really obvious here, or is this a genuine bug? Regular speed doors that don't permit monster activation are rare enough that it's something that could conceivably have been missed. If this is a well-known or documented issue with the Hexen format, it's not one I've come across yet.
[Hexen_Format_Mon_Doors_E1M1.zip](https://github.com/coelckers/gzdoom/files/6080628/Hexen_Format_Mon_Doors_E1M1.zip)

**Comment by coelckers** [comment]
This is a documented feature inherited frm ZDoom. There are two activation modes that can be set in MAPINFO - lax and strict.
The lax mode was what early ZDoom implemented generally but this created so many problems with Doom format maps that the strict mode was added. However, due to the large number of already existing mods at that time, we could not set the default for Hexen format maps to strict or many of these older maps would have broken. 
But when UDMF was added we did not have to preserve this and could set the default properly to strict.

If you need strict activation, add 'strictmonsteractivation' to your MAPINFO for all maps that need it.

**Comment by Acts19quiz** [comment]
So this flag is for Hexen format maps and not just UDMF. That makes sense, that the oldest ZDoom fork out there is the aberration and not every other source port out there. Thanks for the clarification.
