### ISSUE TITLE
Add ZMusic as a submodule

### ISSUE THREAD

**Issue by nikitalita** [coelckers/gzdoom#1354]
Now that GZDoom is using submodules in its repo, I'd like to see ZMusic be added as a submodule (with an optional flag to turn it off and use a system/custom installation) to make this a bit easier to compile from a fresh clone.

**Comment by Cacodemon345** [comment]
If that's to be done it should be done in such a way that it doesn't inconvenience users doing a simple git clone.

**Comment by madame-rachelle** [comment]
ZMusic is probably far from the only thing that should be added as a submodule. But not everyone likes submodules in git, and unfortunately, that is for good reason. I think it mostly comes down to determining when the pros outweigh the cons of doing so it is time to do it.

**Comment by nikitalita** [comment]
> ZMusic is probably far from the only thing that should be added as a submodule. But not everyone likes submodules in git, and unfortunately, that is for good reason. I think it mostly comes down to determining when the pros outweigh the cons of doing so it is time to do it.

Understandable, but I think in this case it's a good candidate. It's a build requirement, it's not available in most system repositories or vcpkg, and the CI already requires it be pinned to a certain version.

**Comment by madame-rachelle** [comment]
> It's a build requirement, it's not available in most system repositories or vcpkg, and the CI already requires it be pinned to a certain version.

This is exactly why submodules are hated in git.

Some people easily understand you have to check out submodules automatically when cloning and fetching a repository. It's not obvious to a Git noob though, and when their compile doesn't work one can spend hours trying to figure out the problem before finally understanding that they need to use submodules to get it. At least for the widescreen project it was fairly harmless (you just don't get an optional archive), but imagine how much hassle it would be if you didn't know you needed a submodule for ZMusic or how to activate it.

I'm not against the idea, I'm just saying submodules come with baggage. And I really hate the way Git forces you to activate them in order to use them.

**Comment by nikitalita** [comment]
> Some people easily understand you have to check out submodules automatically when cloning and fetching a repository. It's not obvious to a Git noob though, and when their compile doesn't work one can spend hours trying to figure out the problem before finally understanding that they need to use submodules to get it. At least for the widescreen project it was fairly harmless (you just don't get an optional archive), but imagine how much hassle it would be if you didn't know you needed a submodule for ZMusic or how to activate it.

I mean... people already get confused by the ZMusic requirement. It's not mentioned in the wiki article that you have to build and install that first and then point to it for the GZDoom build via a CMake param. I had to look at the CI scripts to figure out how to do that. Even if the article were updated to tell you how to do that, I would think that saying "Clone this repo with `git clone --recurse-submodules https://github.com/coelckers/gzdoom`" or "Run `git submodule update --init` after cloning" in the README or something would be far less confusing and less of a hassle?

**Comment by madame-rachelle** [comment]
Again - I am not against your idea, I just don't think it's the perfect "silver bullet". And because of that, I think it should be approached more carefully.

Someone had the idea of remaking the CMake project completely, and I would prefer that to be done first, before we decide what to submodule and what not to, in terms of libraries. The system we have right now is not good, I know that, but it's better to make a good decision when you have all the cards on the table.

**Comment by Blzut3** [comment]
Done in pull request #1401.
