### ISSUE TITLE
Shape2D Objects causing massive stuttering during clearing phase of the GC

### ISSUE THREAD

**Issue by doomedxx** [coelckers/gzdoom#1415]
GZDoom 4.6.0 introduced a problem where our UI would stutter after being used for a few seconds. The problem seems to be related to Shape2D where, upon creating a large number of objects, the game would start freezing for a second or two because of the high number of objects that are immediately destroyed after rendering.

ZForms was used for this, however, GZDoom 4.5.0 did not have this issue and still runs fine.

**Comment by nashmuhandes** [comment]
Yes, old version of ZForms (v1.0) has issues with the GC. The problem actually has existed even before GZDoom 4.6.0, though it does depend on how/when it manifests.

There is an open discussion here: https://forum.zdoom.org/viewtopic.php?f=2&t=70492 but I'm not sure if this will be fixed any time soon, TBH.

In the mean time, however, ZForms v2.0 has already fixed the GC issues (detailed here: https://forum.zdoom.org/viewtopic.php?p=1176423#p1176423), but ZForms v2.0 also has a slight API change from v1.0. The ZForms repo on Gitlab has the latest version. Although it isn't labelled as stable yet, it is highly recommended to switch over to the new API.

**Comment by coelckers** [comment]
The problem here is totally unrelated. Shape2D had a major design flaw that calling Destroy would not free its data, so it'd gobble up massive amounts of GPU-side buffers and never free them until collected. Then, when GC hits, all those stale Shape2D objects would have to be freed all at once - each single one also destroying a vertex buffer on the GPU. Yes, this would pretty much kill performance quite efficiently.

I added an OnDestroy method so the user can free the data once it's no longer needed, but this is the user's responsibility. If you just throw the object away by nulling its reference the same thing will happen again.
Sorry, that's all I can do here - care must be taken when using this class.

**Comment by coelckers** [comment]
Also keep in mind that the object has to be retained for one frame after using it in a draw call! The buffer needs to be present until the object gets rendered. 
Setting up a shape, drawing it and nulling the pointer is totally undefined, even without this change. It may free the buffer before the renderer has any chance to handle it.
