### ISSUE TITLE
Crash when using Corruption of Cards 4.6.1

### ISSUE THREAD

**Issue by RealRexen** [coelckers/gzdoom#1431]
I seem to get a crash when using CorruptionCards-v2.1d.pk3 or any other 2.1 version I have, this doesn't happen on 4.6 stable and seems like 4.7pre is having issues with the mod, crashes on map start (titlemaps seem to be uneffected). This is on the latest windows 11 build and with autoload disable.  Mod can be found here https://forum.zdoom.org/viewtopic.php?f=43&t=67939 
Tested with gzdoom-x64-g4.7.0pre-74-ge02690af5. 
Crash Dump: 
[CrashReport1.zip](https://github.com/coelckers/gzdoom/files/6803976/CrashReport1.zip)
Filing this here in case something is broken with how gzdoom handles mods as this works in the latest stable of gzdoom

**Comment by alexey-lysiuk** [comment]
It started with https://github.com/coelckers/gzdoom/commit/9b4a4157b958843250591c68e548532f5cb8d19e. The given mod adds and destroys 2D shapes during the single gametic. When shape is about to be [rendered](https://github.com/coelckers/gzdoom/blob/2d0a876ab1ed3d05ad8b3d552a266fed80605e0d/src/common/rendering/hwrenderer/hw_draw2d.cpp#L183), it's vertex buffer is [already cleared](https://github.com/coelckers/gzdoom/blob/9b4a4157b958843250591c68e548532f5cb8d19e/src/common/2d/v_2ddrawer.cpp#L537).

**Comment by coelckers** [comment]
It was just lucky coincidence that it did not crash before. The renderer operated on an already destroyed object and had the GC struck at the right time it would have crashed just the same.

**Comment by CutmanMike** [comment]
I'm happy to change the mod if I can figure out what part is causing the crash (and hopefully isn't something vital to the menu animations)

**Comment by alexey-lysiuk** [comment]
> I'm not really sure how to best deal with this.

The most straightforward solution is to skip drawing if `DShape2D::buffers` is empty. No vertex buffer means that a shape is already destroyed, and engine cannot do anything about it.
Of course, this will break mods that creates 2D shapes that live for one gametic. For example, Corruption Cards will have a background missing on the selection screen. Definitely, it's better than a crash. Mods still need to be updated though.

**Comment by RealRexen** [comment]
Updated title since I got around to testing with 4.6.1 and it happens there.

**Comment by Gutawer** [comment]
When Shape2D was first put into the engine by Marisa it would just copy the vertex data over to the global 2D drawer's buffers, a few months back I PR'd this commit https://github.com/coelckers/gzdoom/commit/276cdde1125bf6f3fec1655c75204761e1bf3986 which changed this so that Shape2Ds would keep their vertex info directly in their own GPU buffers - in cases with large Shape2Ds (like what ZForms creates) this ends up being a major performance improvement as the GPU isn't constantly being uploaded to, but at the time I didn't realise that this would break Shape2Ds which were drawn on the same frame they were destroyed (which was previously a completely fine operation as the data was copied to the draw list before the Shape2D was destroyed).

As such breaking backwards compatibility here is probably not a good option - a lot of mods in the past have used Shape2D like this, before the `DTA_Rotate` option was added (it was used for rotating rectangles).

In my opinion what makes the most sense as a quick fix here would be to replace `TArray<F2DVertexBuffer> buffers;` in DShape2D with something more akin to `TArray<std::shared_ptr<F2DVertexBuffer>> buffers;` - that way the `F2DVertexBuffer`s will outlive the DShape2D but still only exist for as long as the drawing code needs them to.

**Comment by Gutawer** [comment]
https://github.com/coelckers/gzdoom/pull/1446 should fix this (and does, on my system with the mod in question).
