### ISSUE TITLE
[BUG] window has wrong color & dimensions

### ISSUE THREAD

**Issue by x3003** [coelckers/gzdoom#1628]
### GZDoom version

gzdoom-x64-g4.8pre-460-gc8156fa58

### Which game are you running with GZDoom?

Other

### What Operating System are you using?

Windows 10

### Please describe your specific OS version

Windows 10

### Relevant hardware info

AMD r5, gtx 1060

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

When starting blade of agony with gzdoom-x64-g4.8pre-460-gc8156fa58 the first window has the wrong color & dimensions.
The **last** version that worked correctly was gzdoom-x64-g4.8pre-440-gbb42e541e

This is how it normally looks (windowed):

![boa_normal_window](https://user-images.githubusercontent.com/77861029/172476507-d26c5505-2658-4430-9c21-538d906dd78d.jpg)

This is how it now looks (fullscreen):

![boa_fullscreen_orso](https://user-images.githubusercontent.com/77861029/172476646-fa54c033-d179-4009-b7eb-be0b80b9a60e.jpg)

### Steps to reproduce the behaviour.

Explain how to reproduce
1. Start boa
2. Look at window....
3.

**Comment by x3003** [comment]
Yeah, I have gamma correction on. But why apply it to the introwindow/screen ?

**Comment by Gaerzi** [comment]
Because now they use game code.

The gist is that previously they used special code that was only implemented to work on Windows. This has been changed so that now it can work on all platforms and the old limitations (like only being able to use the weird 16-color planar format for Hexen-style intros like the one used in W:BOA) can be removed.

As a result, it is now scaled to the size of the game screen since it is the game screen, and it uses the game's visual settings.

**Comment by x3003** [comment]
Thx for explaining. My monitor is so bright I have to set it to 50%. So any program/game that uses fullscreen is too dark by default, so I turned the gamma up a bit.

**Comment by Tormentor667** [comment]
I wonder: Has there been a fix regarding the black borders in the meantime?
