### ISSUE TITLE
[BUG] Fails to compile (lto): GlslangToSpv.cpp:4217:41: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]

### ISSUE THREAD

**Issue by vilhelmgray** [coelckers/gzdoom#1673]
### GZDoom version

GZDoom 4.8.2

### What Operating System are you using?

Linux x86_64

### Please describe your specific OS version

Gentoo Linux

### Have you checked that no other similar issue already exists?

- [X] I have searched and not found similar issues.

### A clear and concise description of what the bug is.

Building GZDoom 4.8.2 with GCC 12.1.1 Link Time Optimization (LTO) switches results in compilation error of the following form:
```
gzdoom-g4.8.2/libraries/glslang/spirv/GlslangToSpv.cpp:4217:41: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
 4217 |                     unsigned literal = *reinterpret_cast<unsigned*>(&floatValue);
      |                                         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
make[2]: *** [libraries/glslang/spirv/CMakeFiles/SPIRV.dir/build.make:76: libraries/glslang/spirv/CMakeFiles/SPIRV.dir/GlslangToSpv.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:474: libraries/glslang/spirv/CMakeFiles/SPIRV.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

### Steps to reproduce the behaviour.

Unpack GZDoom 4.8.2 source tarball and change to the extracted directory. Execute the following commands:
```
$ cmake -DCMAKE_CXX_FLAGS="-flto -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing" .
$ make
```

### Provide a Log

Downstream Gentoo bug: https://bugs.gentoo.org/858749
Build log from Gentoo bug: https://858749.bugs.gentoo.org/attachment.cgi?id=792122

**Comment by coelckers** [comment]
This is your compiler's problem that it chooses to consider valid syntax an error and not a warning. What made it to enable the option to treat a warning as an error?

**Comment by vilhelmgray** [comment]
I'll resolve this by adjusting the compiler flags to not treat these are errors.

**Comment by chewi** [comment]
I'll attempt to explain this, although I'm mostly guessing here.

In the quest for ever better performance, it is becoming increasingly popular to build with Link Time Optimisation. That cannot be applied when you fall foul of the [One Definition Rule](https://gieseanw.wordpress.com/2018/10/30/oops-i-violated-odr-again/). This is normally treated as a warning, as not being able to apply an optimisation is not a big deal, but it has been upgraded to an error here to help address the issue.

The Gentoo QA team have been trying this on all our different packages and filing Gentoo bugs about them. I haven't personally raised this with any upstreams yet. If you don't care, that's fair enough, and I wouldn't expect you to in this case because the issue is in a bundled library. Perhaps it'll hit the same issue in actual GZDoom code further down the line though.

**Comment by coelckers** [comment]
I'll be blunt here: If this is so important to the Gentoo team that they consider it ok to break code that works everywhere else I'll just declare that distro unsupported if it hits again.

**Comment by thesamesam** [comment]
Someone reported a bug for a severe compiler warning that was produced by a test run. These flags are not being set globally in Gentoo. If you think it's not valid, that's fine. But the real fix would be to either fix the strict aliasing issue or set -fno-strict-aliasing in your build.
