### ISSUE TITLE
Crashing on Models

### ISSUE THREAD

**Issue by SnowHaze** [coelckers/gzdoom#189]
I didn't want to report this as an issue as it could be the result of bad drivers that I can not update, attached is a crash report from an older version of gzdoom (from during the zscript development), as the latest builds behave differently on the issue.

When any actor with a model spawns (including actors that are already placed in maps), gzdoom's window simply vanishes and the process stays in Background Processes in the task manager until I kill it, in the older version I get a crash log instead.

[CrashReportsw.zip](https://github.com/coelckers/gzdoom/files/688435/CrashReportsw.zip)

**Comment by coelckers** [comment]
That old crash log is as good as useless, especially if behavior on current builds is different.

Since your hardware is at the absolute bottom end for the modern render path, what does happen if you start GZDoom with '-glversion 2' to force it down to the legacy support path?
If that helps it may be necessary to force these old Intel chipsets down to that.
